title: "Generalization Papers"
description: "Collecting DL/ML papers of personal interest"
baseurl: "/generalization-papers.git"
url: "https://github.com/aiulus"

# Build settings
theme: minima

# Add plugins & custom configuration
# TODO