title: "Generalization Papers"
description: "Collecting recent papers analyzing generalization behavior of Deep Neural Networks"
baseurl: "/generalization-papers.git"
url: "https://github.com/aiulus"

# Build settings
theme: minima

# Add plugins & custom configuration
# TODO